---
kind: pipeline
name: default

steps:
  - name: setup
    image: node:latest
    when:
      event: [pull_request]
    commands:
      - yarn install

  - name: build
    image: node:latest
    when:
      event: [pull_request]
    depends_on:
      - setup
    commands:
      - yarn build


  - name: prettier
    image: node:latest
    when:
      event: [pull_request]
    depends_on:
      - setup
    commands:
      - yarn prettier

  - name: lint
    image: node:latest
    when:
      event: [pull_request]
    depends_on:
      - setup
    commands:
      - yarn lint
