version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: Charity
    volumes:
       - db-data:/data/db
    ports:
      - 27017:27017

  app:
    build: .
    restart: always
    ports:
      - 3001:3000
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    links:
      - "mongo"
volumes:
  db-data: